#!/bin/bash

echo "%c => Character"
echo "%d => Signed integer"
echo "%e => Scientific notation of floats"
echo "%f => Float values"
echo "%g => Similar to %e"
echo "%hi => Signed integer (short)"
echo "%hu => Unsigned Integer (short)"
echo "%i => Unsigned integer"
echo "%l => Long"
echo "%lf => Double"
echo "%Lf => Long double"
echo "%lu => Unsigned int or unsigned long"
echo "%lli => Long long"
echo "%llu => Unsigned long long"
echo "%o => Octal representation"
echo "%p => Pointer"
echo "%s => String"
echo "%u => Unsigned int"
echo "%x => Hexadecimal representation"
echo "%n => Prints nothing"
echo "%% => Prints % character"